### ISSUE TITLE
redirect is not working when the method is chenged

### ISSUE THREAD

**Issue by linoymiz** [linoymiz/AlbumY#1]
In Delete route I try to navigate back to the get('/:albumId') route and it is not happenning.
https://github.com/linoymiz/AlbumY/blob/c37482fdc6af9ac19b749a3d014ba96963b235bf/server/routers/album.js#L146-L147

In Post('/add') I do manage to redirect to the same get route. why?

**Comment by raz-cohen** [comment]
What exactly do happen?
Have you tried to debug the "url" var both in the back (the url var you pass here: `res.redirect(url)`) & front (the response you get from this backend route)?

**Comment by linoymiz** [comment]
I understood that from delete request (which works fine and delete the right element) it could not redirect to other HTTP request with different method. even changing the method speciffically doesn't help.

from network debugging got to this for the working 'add' post route when redirecting to the get route:
![image](https://user-images.githubusercontent.com/49729049/158009389-a048c93d-63a7-4cc5-9bbc-22b081c6ce6a.png)
![image](https://user-images.githubusercontent.com/49729049/158009532-9bfaa1fa-ff52-4f52-872d-3a4bc17aec6d.png)

and the redirect from the delete looks like this:
![image](https://user-images.githubusercontent.com/49729049/158009561-760660f7-39d5-4dfb-85dd-3fdbe0a19ace.png)
![image](https://user-images.githubusercontent.com/49729049/158009587-3f09fc71-9db8-4050-8ef4-651a920e3640.png)
![image](https://user-images.githubusercontent.com/49729049/158009599-decfcef1-a048-4233-b6f2-c264b4d725b5.png)

**Note*** that I changed the code a bit for this
*post 'add'*
https://github.com/linoymiz/AlbumY/blob/1e5b4232c6794a1450c2f184f2c0f693cf7fcc26/server/routers/album.js#L87
https://github.com/linoymiz/AlbumY/blob/1e5b4232c6794a1450c2f184f2c0f693cf7fcc26/server/routers/album.js#L117

*delete*
https://github.com/linoymiz/AlbumY/blob/1e5b4232c6794a1450c2f184f2c0f693cf7fcc26/server/routers/album.js#L129
https://github.com/linoymiz/AlbumY/blob/1e5b4232c6794a1450c2f184f2c0f693cf7fcc26/server/routers/album.js#L153-L160

which prints the successfully msg and not the error in the catch block.

**Comment by raz-cohen** [comment]
I think I might have got your problem right.
Anyway, redirecting the client using the backend response is a bad approach.
Everything related to handling the client side - should (ofc) be handled at the client side.
Backend should only handle the back-end logic.
You can re-write your code & handle the redirect from the front, according to the response http code (success, failed etc..).

**Comment by linoymiz** [comment]
changed it to res.send as suggested, and added in client side the try and catch (inner one)
https://github.com/linoymiz/AlbumY/blob/df48902f2b549f869ada8c6153b947df8edde8ef/client/src/components/sub-components/album.js#L10-L34

but all works fine and it gives me the requested album. it is just that I want to re-render the album page so I can see the image was indeed deleted.
get this message in browser:
![image](https://user-images.githubusercontent.com/49729049/158017099-95b15abe-e665-4e46-8aa3-b0d20f7e3022.png)
which is what I screenshot deeply before.
and the message is from here:
https://github.com/linoymiz/AlbumY/blob/df48902f2b549f869ada8c6153b947df8edde8ef/client/src/components/sub-components/albumPics.js#L33-L41

and in backend it is showing:
![image](https://user-images.githubusercontent.com/49729049/158017170-2e5c9e2e-a857-4475-817b-a69015e9320e.png)

which means I don't get to the get router.
