### ISSUE TITLE
sending the images along with the album id to the get route

### ISSUE THREAD

**Issue by linoymiz** [linoymiz/AlbumY#2]
in one album I have its own pictures array. when I get to the album page (not the home page which is list of albums) and navigate to the get('/:albumId') it console log the album id but after finishing finding it in the DB it re-running that get route for each picture in the album.
another thing is that the pictures are not rendered good (get the 'alt' ), unlike in home page. 
 
  https://github.com/linoymiz/AlbumY/blob/c37482fdc6af9ac19b749a3d014ba96963b235bf/server/routers/album.js#L39

**Comment by raz-cohen** [comment]
> when I get to the album page (not the home page which is list of albums) and navigate to the get('/:albumId') it console log the album id but after finishing finding it in the DB it re-running that get route for each picture in the album.
> 
> https://github.com/linoymiz/AlbumY/blob/c37482fdc6af9ac19b749a3d014ba96963b235bf/server/routers/album.js#L39

Not sure that I understand what the problem is..


> another thing is that the pictures are not rendered good (get the 'alt' ), unlike in home page.
> 
> https://github.com/linoymiz/AlbumY/blob/c37482fdc6af9ac19b749a3d014ba96963b235bf/server/routers/album.js#L39

And here, you're referring to "alt" which is property of image element in the DOM but this file is related to backend..
Please let me know a bit further regarding this issue

**Comment by linoymiz** [comment]
> > another thing is that the pictures are not rendered good (get the 'alt' ), unlike in home page.
> > https://github.com/linoymiz/AlbumY/blob/c37482fdc6af9ac19b749a3d014ba96963b235bf/server/routers/album.js#L39
> 
> **And here, you're referring to "alt" which is property of image element in the DOM but this file is related to backend.. Please let me know a bit further regarding this issue**

yes but I suppose to get that image from the backend to show it in the frontend like so:
![image](https://user-images.githubusercontent.com/49729049/158010192-6a4ac714-eb93-4986-ab55-548d8b80d3ae.png)

and in album page I get the alt of it:
![image](https://user-images.githubusercontent.com/49729049/158010234-f69df5b5-3ba7-428d-9c6b-bc7208295111.png)

the pictures have this structure and data:
![image](https://user-images.githubusercontent.com/49729049/158010174-1d7ccd53-a846-48a3-9da2-8701fab75f4a.png)

**Comment by raz-cohen** [comment]
> the pictures have this structure and data: ![image](https://user-images.githubusercontent.com/49729049/158010174-1d7ccd53-a846-48a3-9da2-8701fab75f4a.png)

Well, first of all the alt text does not looks like a good alt text..
But lets say you do want to use this kind of text to the alt:
can you please refer me to the file (in the front) which handle the render of that object?
